import java.util.Scanner;

public class ManageExceptions {
	public void printDivide(){
		Scanner scanner = new Scanner(System.in);
		System.out.print("Escribe el primer número");
		int a = scanner.nextInt();

		System.out.print("Escribe el segundo número");
		int b = scanner.nextInt();
		
		try {
		System.out.println("El resultado de l división es: " + (a/b));
		String[] nombres = {"Rosy", "José", "Ivan"};
		System.out.println("nombres[0]: " + nombres[0]);
		System.out.println("nombres[1]: " + nombres[1]);
		System.out.println("nombres[2]: " + nombres[2]);
		System.out.println("nombres[3]: " + nombres[3]);
		}catch (ArithmeticException e) {
			System.out.println("Ningún número puede ser cero");
		}catch (IndexOutOfBoundsException e) {
		System.out.println("No existe ese índice en el arreglo");
		}catch (Exception e) {
		System.out.println("Ocurrió otro error " + e);
		}finally {
			scanner.close();
		}//finally
		
		}//printDivide
}//class ManageExceptions
